---
# Install OS specific beats

- name: Include specific Beats
  include: beats-{{ ansible_os_family }}.yml

#Configuration file for beats
- name: Beats configuration
  include: beats-config.yml

# Make sure the service is started, and restart if necessary
- name: unix - Start beats service
  service: name={{ beat }} state=started enabled=yes
  when: os_type == 'unix' and start_service
  register: beats_started

- name: win - Install beats service with nssm
  win_nssm:
    name: "{{ beat }}"
    state: present
    application: "{{ beats_home_dir }}\\{{ beat }}.exe"
    arguments: '-c "{{ conf_file }}" {{ daemon_args }}'
  when: not use_repository and os_type == 'win' and start_service

- name: win - Start beats service
  win_service:
    name: "{{ beat }}"
    state: started
    start_mode: auto
  when: os_type == 'win' and start_service
  register: beats_started
